#!/usr/bin/env bash
set -euo pipefail

: "${CUDA_VISIBLE_DEVICES:=0,1}"
: "${MODELS:=./checkpoints/vision_action_vlabench}"
: "${WORLD_TEACHER_PATH:=./checkpoints/world_teacher_vlabench}"
: "${TRAIN_METAS_PATH:=./data/vlabench_primitive_ft_lerobot/meta/info.json}"
: "${VLABENCH_CAMERA_ORDER:=image,second_image,wrist_image}"
: "${OUTPUT_DIR:=./checkpoints/bridge_wa_vlabench}"
: "${ACTION_MODE:=ee6d}"
: "${BATCH_SIZE:=128}"
: "${LEARNING_RATE:=1e-4}"
: "${ITERS:=100000}"
: "${SAVE_INTERVAL:=25000}"
: "${LOG_INTERVAL:=20}"
: "${FUTURE_TOKEN_COUNT:=4}"
: "${FUTURE_POOL_HW:=2}"
: "${CHANGE_TOKEN_COUNT:=16}"
: "${CHANGE_MAP_POOL_HW:=4}"
: "${FLOW_TOKEN_COUNT:=16}"
: "${FLOW_MAP_POOL_HW:=4}"
: "${BRIDGE_NUM_INJECTED_LAYERS:=4}"
: "${BRIDGE_MODULATION_SCALE:=0.1}"
: "${BRIDGE_CHANGE_BIAS_SCALE:=1.0}"
: "${BRIDGE_FLOW_BIAS_SCALE:=1.0}"
: "${FUTURE_DISTILL_WEIGHT:=0.1}"
: "${FUTURE_DISTILL_COSINE_WEIGHT:=0.1}"
: "${CHANGE_DISTILL_WEIGHT:=0.1}"
: "${CHANGE_DISTILL_COSINE_WEIGHT:=0.1}"
: "${FLOW_DISTILL_WEIGHT:=0.1}"
: "${FLOW_DISTILL_COSINE_WEIGHT:=0.1}"
: "${TEACHER_FUTURE_STEPS:=10}"
: "${TEACHER_CACHE_DIR:=./cache/bridge_wa/vlabench_primitive_ft_lerobot}"
: "${FLOW_WORKERS:=0}"
: "${TRAIN_LAST_N_BLOCKS:=24}"
: "${MIXED_PRECISION:=bf16}"
: "${WARMUP_STEPS:=2000}"
: "${LR_SCHEDULER_TYPE:=cosine}"
: "${MIN_LR_RATIO:=0.1}"
: "${BRIDGE_GUIDANCE_SOURCE:=teacher}"
: "${BRIDGE_GUIDANCE_BLEND_RATIO:=0.7}"

mkdir -p "$(dirname "${OUTPUT_DIR}")" ./log_a800
LOG_FILE="${LOG_FILE:-./log_a800/train_bridge_wa_vlabench_bs${BATCH_SIZE}.log}"

CMD=(
  accelerate launch
  --mixed_precision "${MIXED_PRECISION}"
  scripts/train_bridge_wa.py
  --models "${MODELS}"
  --world_teacher_path "${WORLD_TEACHER_PATH}"
  --train_metas_path "${TRAIN_METAS_PATH}"
  --vlabench_camera_order "${VLABENCH_CAMERA_ORDER}"
  --action_mode "${ACTION_MODE}"
  --output_dir "${OUTPUT_DIR}"
  --batch_size "${BATCH_SIZE}"
  --learning_rate "${LEARNING_RATE}"
  --iters "${ITERS}"
  --save_interval "${SAVE_INTERVAL}"
  --log_interval "${LOG_INTERVAL}"
  --future_token_count "${FUTURE_TOKEN_COUNT}"
  --future_pool_hw "${FUTURE_POOL_HW}"
  --change_token_count "${CHANGE_TOKEN_COUNT}"
  --change_map_pool_hw "${CHANGE_MAP_POOL_HW}"
  --flow_token_count "${FLOW_TOKEN_COUNT}"
  --flow_map_pool_hw "${FLOW_MAP_POOL_HW}"
  --bridge_num_injected_layers "${BRIDGE_NUM_INJECTED_LAYERS}"
  --bridge_modulation_scale "${BRIDGE_MODULATION_SCALE}"
  --bridge_change_bias_scale "${BRIDGE_CHANGE_BIAS_SCALE}"
  --bridge_flow_bias_scale "${BRIDGE_FLOW_BIAS_SCALE}"
  --future_distill_weight "${FUTURE_DISTILL_WEIGHT}"
  --future_distill_cosine_weight "${FUTURE_DISTILL_COSINE_WEIGHT}"
  --change_distill_weight "${CHANGE_DISTILL_WEIGHT}"
  --change_distill_cosine_weight "${CHANGE_DISTILL_COSINE_WEIGHT}"
  --flow_distill_weight "${FLOW_DISTILL_WEIGHT}"
  --flow_distill_cosine_weight "${FLOW_DISTILL_COSINE_WEIGHT}"
  --teacher_future_steps "${TEACHER_FUTURE_STEPS}"
  --flow_workers "${FLOW_WORKERS}"
  --train_last_n_blocks "${TRAIN_LAST_N_BLOCKS}"
  --warmup_steps "${WARMUP_STEPS}"
  --lr_scheduler_type "${LR_SCHEDULER_TYPE}"
  --min_lr_ratio "${MIN_LR_RATIO}"
  --bridge_guidance_source "${BRIDGE_GUIDANCE_SOURCE}"
  --bridge_guidance_blend_ratio "${BRIDGE_GUIDANCE_BLEND_RATIO}"
)
if [[ -n "${TEACHER_CACHE_DIR}" ]]; then
  CMD+=(--teacher_cache_dir "${TEACHER_CACHE_DIR}")
fi

printf '[bridge_wa-vlabench] cmd=' | tee -a "${LOG_FILE}"
printf ' %q' "${CMD[@]}" | tee -a "${LOG_FILE}"
printf '\n' | tee -a "${LOG_FILE}"
nohup env CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES}" "${CMD[@]}" >> "${LOG_FILE}" 2>&1 &
echo "[bridge_wa-vlabench] pid=$!" | tee -a "${LOG_FILE}"
echo "[bridge_wa-vlabench] log= ${LOG_FILE}" | tee -a "${LOG_FILE}"
